language: ruby
rvm:
  - 2.1.1
  - rbx-2.1.1
  - jruby-19mode

matrix:
  exclude:
    - rvm: jruby-19mode
      env: DB=sqlite
    - rvm: rbx-2.1.1
      env: DB=sqlite
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1

branches:
  only:
    - master

script: "CODECLIMATE_REPO_TOKEN=ab8d492d1d82e2b594bb4c4d6e712d67bae2ef3e117f0b25fbca7b31b85abc20 bundle exec rake test"

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite

before_script:
  - psql -c 'create database data_store_test;' -U postgres
  - mysql -e 'create database data_store_test'
