language: ruby
rvm:
  - 2.1.0
  - rbx-2.1.1
  - jruby-19mode

matrix:
  exclude:
    - rvm: jruby-19mode
      env: DB=sqlite
    - rvm: rbx-19mode
      env: DB=sqlite
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

branches:
  only:
    - master

script: "bundle exec rake test"

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite

before_script:
  - psql -c 'create database data_store_test;' -U postgres
  - mysql -e 'create database data_store_test'
