language: ruby
rvm:
  - 1.9.3
  - rbx-19mode

branches:
  only:
    - master

script: "bundle exec rake test"

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite

before_script:
  - psql -c 'create database data_store_test;' -U postgres
  - mysql -e 'create database data_store_test'
