postgres:
  adapter: postgres
  username: postgres
  password:
  database: data_store_test
  pool: 5
  timeout: 5000
  host: localhost

sqlite:
  adapter: sqlite
  database: db/data_store.db

mysql:
  adapter: mysql2
  username: root
  password:
  database: data_store_test
  pool: 5
  timeout: 5000
  host: localhost